export const data = [
  { id: 1, nama: "Chocolate Chip Muffins", harga: 3.99, stock: 1 },
  { id: 2, nama: "Magnetic Puzzle Board", harga: 24.99, stock: 2 },
  { id: 3, nama: "Roasted Garlic Butter", harga: 3.29, stock: 3 },
  { id: 4, nama: "Smart Thermos", harga: 39.99, stock: 4 },
  { id: 5, nama: "Maple Glazed Carrots", harga: 3.29, stock: 5 },
  { id: 6, nama: "Frozen Mixed Vegetables", harga: 1.99, stock: 6 },
  { id: 7, nama: "Peach Yogurt", harga: 1.29, stock: 7 },
  { id: 8, nama: "Compact Digital Camera", harga: 249.99, stock: 8 },
  { id: 9, nama: "Pet Bed with Removable Cover", harga: 49.99, stock: 9 },
  { id: 10, nama: "Memory Foam Mattress Pad", harga: 69.99, stock: 10 },
  { id: 11, nama: "Creamy Coleslaw Mix", harga: 2.39, stock: 11 },
  { id: 12, nama: "Maple Almond Granola", harga: 5.49, stock: 12 },
  { id: 13, nama: "Cream Cheese", harga: 2.69, stock: 13 },
  { id: 14, nama: "Chickpea Flour", harga: 3.29, stock: 14 },
  {
    id: 15,
    nama: "Smart Water Bottle with Hydration Reminder",
    harga: 39.99,
    stock: 15,
  },
  { id: 16, nama: "Inspirational Wall Art", harga: 24.99, stock: 16 },
  { id: 17, nama: "Gingerbread House Kit", harga: 6.99, stock: 17 },
  { id: 18, nama: "Compact Hair Dryer", harga: 29.99, stock: 18 },
  { id: 19, nama: "Handheld Garment Steamer", harga: 34.99, stock: 19 },
  { id: 20, nama: "Classic Bagels", harga: 2.99, stock: 20 },
];
